[theme]
base = "dark"
backgroundColor = "#0a192f"
textColor = "#EAEAEA"
secondaryBackgroundColor = "#0a192f"
primaryColor = "#FFA500"
font = "sans serif"
showWidgetBorder=true

[theme.sidebar]
backgroundColor = "#4782bb"
textColor = "#EAEAEA"
baseRadius="full"